name: nova_store
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  # Firebase
  firebase_core: ^3.8.1
  # Core Dependencies
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3



dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
